# Generated by Django 5.0.3 on 2024-03-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('images', models.TextField()),
                ('vdo_ex', models.TextField()),
                ('vdo_main', models.TextField()),
                ('vdo_main_2', models.TextField()),
                ('vdo_main_3', models.TextField()),
                ('status_list', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
            ],
        ),
    ]
