# Generated by Django 5.0.3 on 2024-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.IntegerField(max_length=3)),
                ('name', models.TextField()),
                ('vdo', models.TextField()),
                ('vdo_2', models.TextField()),
                ('vdo_3', models.TextField()),
                ('part', models.IntegerField(max_length=3)),
            ],
        ),
    ]
