# Generated by Django 5.0.3 on 2024-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_data_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_list',
            name='main_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_list',
            name='part',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_movie',
            name='images',
            field=models.ImageField(upload_to='movie_images'),
        ),
    ]
