# Generated by Django 5.0.3 on 2024-03-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_images_data_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_movie',
            old_name='image',
            new_name='img',
        ),
    ]
