# Generated by Django 5.0.3 on 2024-03-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_rename_image_data_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_movie',
            old_name='img',
            new_name='image',
        ),
    ]
