# Generated by Django 5.0.3 on 2024-03-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_data_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_list',
            name='name',
            field=models.TextField(),
        ),
    ]
