# Generated by Django 5.0.3 on 2024-04-02 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.category'),
        ),
    ]
